In [1]:
import numpy as np

In [2]:
list = [0, 1, 2, 3, 4, 5]

In [3]:
num = np.array(list)

In [4]:
num

array([0, 1, 2, 3, 4, 5])

In [5]:
num = np.array(list, size=(3,3))

TypeError: array() got an unexpected keyword argument 'size'

In [6]:
np.reshape(list, (2,2))

ValueError: cannot reshape array of size 6 into shape (2,2)

In [7]:
A = np.array([0,1,2]).reshape((3L, 1L))

SyntaxError: invalid decimal literal (2963454739.py, line 1)

In [8]:
num.reshape(4, 3)

ValueError: cannot reshape array of size 6 into shape (4,3)

In [9]:
num.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]).reshape(3, 3)

In [11]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.mean(arr)

4.0

In [13]:
np.mean(arr[0])

1.0

In [14]:
print([np.mean(arr[0]), np.mean(arr[1]), np.mean(arr)])

[1.0, 4.0, 4.0]


In [15]:
print([np.mean(arr[0]), np.mean(arr[:, 0]), np.mean(arr)])

[1.0, 3.0, 4.0]


In [16]:
mean = np.array(
      [
        [np.mean(arr(:, 0)), np.mean(arr(:, 1)), np.mean(arr(:, 2))],
        [np.mean(arr(0)), np.mean(arr(1)), np.mean(arr(2))],
        np.mean(arr)
      ]
    )

SyntaxError: invalid syntax (4112266588.py, line 3)

In [17]:
mean = np.array(
      [
        [np.mean(arr[:, 0]), np.mean(arr[:, 1]), np.mean(arr[:, 2])],
        [np.mean(arr[0]), np.mean(arr[1]), np.mean(arr[2])],
        np.mean(arr)
      ]
    )

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [18]:
mean = np.array(
      [
        [np.mean(arr[:, 0]), np.mean(arr[:, 1]), np.mean(arr[:, 2])],
        [np.mean(arr[0]), np.mean(arr[1]), np.mean(arr[2])]
      ]
    )

In [19]:
print(mean)

[[3. 4. 5.]
 [1. 4. 7.]]


In [20]:
mean = [[np.mean(arr[:, 0]), np.mean(arr[:, 1]), np.mean(arr[:, 2])], [np.mean(arr[0]), np.mean(arr[1]), np.mean(arr[2])], np.mean(arr)]

In [21]:
print(mean)

[[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0]


In [22]:
var = [[np.var(arr[:, 0]), np.var(arr[:, 1]), np.var(arr[:, 2])], [np.var(arr[0]), np.var(arr[1]), np.var(arr[2])], np.var(arr)]

In [23]:
print(var)

[[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667]


In [24]:
max = [[np.max(arr[:, 0]), np.max(arr[:, 1]), np.max(arr[:, 2])], [np.max(arr[0]), np.max(arr[1]), np.max(arr[2])], np.max(arr)]

In [25]:
print(max)

[[6, 7, 8], [2, 5, 8], 8]


In [40]:
def calculate(list):
    arr = np.array(list).reshape(3, 3)
    mean = [[np.mean(arr[:, 0]), np.mean(arr[:, 1]), np.mean(arr[:, 2])], [np.mean(arr[0]), np.mean(arr[1]), np.mean(arr[2])], np.mean(arr)]
    var = [[np.var(arr[:, 0]), np.var(arr[:, 1]), np.var(arr[:, 2])], [np.var(arr[0]), np.var(arr[1]), np.var(arr[2])], np.var(arr)]
    std = [[np.std(arr[:, 0]), np.std(arr[:, 1]), np.std(arr[:, 2])], [np.std(arr[0]), np.std(arr[1]), np.std(arr[2])], np.std(arr)]
    max = [[np.max(arr[:, 0]), np.max(arr[:, 1]), np.max(arr[:, 2])], [np.max(arr[0]), np.max(arr[1]), np.max(arr[2])], np.max(arr)]
    min = [[np.min(arr[:, 0]), np.min(arr[:, 1]), np.min(arr[:, 2])], [np.min(arr[0]), np.min(arr[1]), np.min(arr[2])], np.min(arr)]
    sum = [[np.sum(arr[:, 0]), np.sum(arr[:, 1]), np.sum(arr[:, 2])], [np.sum(arr[0]), np.sum(arr[1]), np.sum(arr[2])], np.sum(arr)]
    calculations = f"{{\n\t'mean': {mean},\n\t'variance': {var},\n\t'standard deviation' {std},\n\t'max': {max},\n\t'min': {min},\n\t'sum': {sum}\n}}"
    return calculations

In [41]:
print(calculate([0,1,2,3,4,5,6,7,8]))

{
	'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
	'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667],
	'standard deviation' [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
	'max': [[6, 7, 8], [2, 5, 8], 8],
	'min': [[0, 1, 2], [0, 3, 6], 0],
	'sum': [[9, 12, 15], [3, 12, 21], 36]
}


In [42]:
dict = {
    'mean' = mean,
    'variance' = var,
    'standard deviation' = std,
    'max' = max,
    'min' = min,
    'sum' = sum
}

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (2228101778.py, line 2)

In [43]:
mean = [[np.mean(arr[:, 0]), np.mean(arr[:, 1]), np.mean(arr[:, 2])], [np.mean(arr[0]), np.mean(arr[1]), np.mean(arr[2])], np.mean(arr)]
    var = [[np.var(arr[:, 0]), np.var(arr[:, 1]), np.var(arr[:, 2])], [np.var(arr[0]), np.var(arr[1]), np.var(arr[2])], np.var(arr)]
    std = [[np.std(arr[:, 0]), np.std(arr[:, 1]), np.std(arr[:, 2])], [np.std(arr[0]), np.std(arr[1]), np.std(arr[2])], np.std(arr)]
    max = [[np.max(arr[:, 0]), np.max(arr[:, 1]), np.max(arr[:, 2])], [np.max(arr[0]), np.max(arr[1]), np.max(arr[2])], np.max(arr)]
    min = [[np.min(arr[:, 0]), np.min(arr[:, 1]), np.min(arr[:, 2])], [np.min(arr[0]), np.min(arr[1]), np.min(arr[2])], np.min(arr)]
    sum = [[np.sum(arr[:, 0]), np.sum(arr[:, 1]), np.sum(arr[:, 2])], [np.sum(arr[0]), np.sum(arr[1]), np.sum(arr[2])], np.sum(arr)]


IndentationError: unexpected indent (704761032.py, line 2)

In [44]:
mean = [[np.mean(arr[:, 0]), np.mean(arr[:, 1]), np.mean(arr[:, 2])], [np.mean(arr[0]), np.mean(arr[1]), np.mean(arr[2])], np.mean(arr)]
var = [[np.var(arr[:, 0]), np.var(arr[:, 1]), np.var(arr[:, 2])], [np.var(arr[0]), np.var(arr[1]), np.var(arr[2])], np.var(arr)]
std = [[np.std(arr[:, 0]), np.std(arr[:, 1]), np.std(arr[:, 2])], [np.std(arr[0]), np.std(arr[1]), np.std(arr[2])], np.std(arr)]
max = [[np.max(arr[:, 0]), np.max(arr[:, 1]), np.max(arr[:, 2])], [np.max(arr[0]), np.max(arr[1]), np.max(arr[2])], np.max(arr)]
min = [[np.min(arr[:, 0]), np.min(arr[:, 1]), np.min(arr[:, 2])], [np.min(arr[0]), np.min(arr[1]), np.min(arr[2])], np.min(arr)]
sum = [[np.sum(arr[:, 0]), np.sum(arr[:, 1]), np.sum(arr[:, 2])], [np.sum(arr[0]), np.sum(arr[1]), np.sum(arr[2])], np.sum(arr)]

In [45]:
dict = {
    'mean' = mean,
    'variance' = var,
    'standard deviation' = std,
    'max' = max,
    'min' = min,
    'sum' = sum
}

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (2228101778.py, line 2)

In [46]:
dict = {
    'mean' = [[np.mean(arr[:, 0]), np.mean(arr[:, 1]), np.mean(arr[:, 2])], [np.mean(arr[0]), np.mean(arr[1]), np.mean(arr[2])], np.mean(arr)],
    'variance' = var,
    'standard deviation' = std,
    'max' = max,
    'min' = min,
    'sum' = sum
}

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (3460114133.py, line 2)

In [47]:
dict = {
    'mean' : [[np.mean(arr[:, 0]), np.mean(arr[:, 1]), np.mean(arr[:, 2])], [np.mean(arr[0]), np.mean(arr[1]), np.mean(arr[2])], np.mean(arr)],
    'variance' : var,
    'standard deviation' : std,
    'max' : max,
    'min' : min,
    'sum' : sum
}

In [48]:
print(dict)

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8], 'min': [[0, 1, 2], [0, 3, 6], 0], 'sum': [[9, 12, 15], [3, 12, 21], 36]}


In [49]:
import json

In [50]:
print(json.dumps(dict, indent=4))

TypeError: Object of type int32 is not JSON serializable

In [51]:
calculate([2,6,2,8,4,0,1,5,7])

"{\n\t'mean': [[3.6666666666666665, 5.0, 3.0], [3.3333333333333335, 4.0, 4.333333333333333], 3.888888888888889],\n\t'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666], [3.555555555555556, 10.666666666666666, 6.222222222222221], 6.987654320987654],\n\t'standard deviation' [[3.091206165165235, 0.816496580927726, 2.943920288775949], [1.8856180831641267, 3.265986323710904, 2.494438257849294], 2.6434171674156266],\n\t'max': [[8, 6, 7], [6, 8, 7], 8],\n\t'min': [[1, 4, 0], [2, 0, 1], 0],\n\t'sum': [[11, 15, 9], [10, 12, 13], 35]\n}"

In [52]:
calculate([9,1,5,3,3,3,2,9,0])

"{\n\t'mean': [[4.666666666666667, 4.333333333333333, 2.6666666666666665], [5.0, 3.0, 3.6666666666666665], 3.888888888888889],\n\t'variance': [[9.555555555555555, 11.555555555555557, 4.222222222222222], [10.666666666666666, 0.0, 14.888888888888891], 9.209876543209875],\n\t'standard deviation' [[3.0912061651652345, 3.39934634239519, 2.0548046676563256], [3.265986323710904, 0.0, 3.8586123009300755], 3.0347778408328137],\n\t'max': [[9, 9, 5], [9, 3, 9], 9],\n\t'min': [[2, 1, 0], [1, 3, 0], 0],\n\t'sum': [[14, 13, 8], [15, 9, 11], 35]\n}"

In [53]:
print(calculate([9,1,5,3,3,3,2,9,0]))

{
	'mean': [[4.666666666666667, 4.333333333333333, 2.6666666666666665], [5.0, 3.0, 3.6666666666666665], 3.888888888888889],
	'variance': [[9.555555555555555, 11.555555555555557, 4.222222222222222], [10.666666666666666, 0.0, 14.888888888888891], 9.209876543209875],
	'standard deviation' [[3.0912061651652345, 3.39934634239519, 2.0548046676563256], [3.265986323710904, 0.0, 3.8586123009300755], 3.0347778408328137],
	'max': [[9, 9, 5], [9, 3, 9], 9],
	'min': [[2, 1, 0], [1, 3, 0], 0],
	'sum': [[14, 13, 8], [15, 9, 11], 35]
}
